In [3]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_employee_attrition.csv to cleaned_employee_attrition.csv

In [4]:
import pandas as pd

df = pd.read_csv("cleaned_employee_attrition.csv")

print(df.shape)
df.head()

(49653, 15)

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_full,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,Male,2006,0,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,Male,2007,0,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,Male,2008,0,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,Male,2009,0,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,Male,2010,0,HEADOFFICE

In [5]:
print(df.columns.tolist())

['EmployeeID', 'recorddate_key', 'birthdate_key', 'orighiredate_key', 'terminationdate_key', 'age', 'length_of_service', 'city_name', 'department_name', 'job_title', 'store_name', 'gender_full', 'STATUS_YEAR', 'STATUS', 'BUSINESS_UNIT']

In [6]:
df["STATUS"].value_counts()

STATUS
0    48168
1     1485
Name: count, dtype: int64

In [7]:
X = df.drop("STATUS", axis=1)
y = df["STATUS"]

In [8]:
X.dtypes

EmployeeID              int64
recorddate_key         object
birthdate_key          object
orighiredate_key       object
terminationdate_key    object
age                     int64
length_of_service       int64
city_name              object
department_name        object
job_title              object
store_name              int64
gender_full            object
STATUS_YEAR             int64
BUSINESS_UNIT          object
dtype: object

In [9]:
df["STATUS"].value_counts()

STATUS
0    48168
1     1485
Name: count, dtype: int64

In [10]:
X = df.drop("STATUS", axis=1)
y = df["STATUS"]

print(X.shape)
print(y.shape)

(49653, 14)
(49653,)

In [11]:
X = X.drop([
    "EmployeeID",
    "terminationdate_key"
], axis=1)

In [12]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [13]:
print(X.shape)
X.head()

(49653, 9995)

,age,length_of_service,store_name,STATUS_YEAR,recorddate_key_1/1/2007 0:00,recorddate_key_1/1/2008 0:00,recorddate_key_1/1/2009 0:00,recorddate_key_1/1/2010 0:00,recorddate_key_1/1/2011 0:00,recorddate_key_1/1/2012 0:00,...,job_title_Recruiter,job_title_Shelf Stocker,job_title_Store Manager,job_title_Systems Analyst,job_title_Trainer,job_title_VP Finance,job_title_VP Human Resources,job_title_VP Stores,gender_full_Male,BUSINESS_UNIT_STORES
0,52,17,35,2006,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,53,18,35,2007,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,54,19,35,2008,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,55,20,35,2009,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,56,21,35,2010,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=42)

In [16]:
y_pred = rf.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9984895780888128

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9634
           1       1.00      0.95      0.97       297

    accuracy                           1.00      9931
   macro avg       1.00      0.97      0.99      9931
weighted avg       1.00      1.00      1.00      9931

In [19]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[9634    0]
 [  15  282]]

In [20]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
).head(20)

                            Feature  Importance
0                               age    0.222230
41    recorddate_key_12/1/2014 0:00    0.056510
3                       STATUS_YEAR    0.040996
42    recorddate_key_12/1/2015 0:00    0.030834
1                 length_of_service    0.027114
99     recorddate_key_6/1/2012 0:00    0.010567
21    recorddate_key_10/1/2014 0:00    0.007778
66     recorddate_key_3/1/2009 0:00    0.007078
85     recorddate_key_5/1/2008 0:00    0.006978
52   recorddate_key_12/31/2015 0:00    0.006571
61     recorddate_key_2/1/2014 0:00    0.006421
34    recorddate_key_12/1/2007 0:00    0.006311
64     recorddate_key_3/1/2007 0:00    0.006278
43   recorddate_key_12/31/2006 0:00    0.006216
24    recorddate_key_11/1/2007 0:00    0.006198
38    recorddate_key_12/1/2011 0:00    0.006156
28    recorddate_key_11/1/2011 0:00    0.006055
5      recorddate_key_1/1/2008 0:00    0.005914
121    recorddate_key_8/1/2014 0:00    0.005780
74     recorddate_key_4/1/2007 0:00    0.005734

In [21]:
X = df.drop([
    "STATUS",
    "EmployeeID",
    "recorddate_key",
    "birthdate_key",
    "orighiredate_key",
    "terminationdate_key",
    "STATUS_YEAR"
], axis=1)

y = df["STATUS"]

In [22]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=42)

In [25]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9856006444466822
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      9634
           1       0.90      0.59      0.71       297

    accuracy                           0.99      9931
   macro avg       0.94      0.79      0.85      9931
weighted avg       0.98      0.99      0.98      9931

In [26]:
y.value_counts(normalize=True)

STATUS
0    0.970092
1    0.029908
Name: proportion, dtype: float64

In [27]:
from sklearn.ensemble import RandomForestClassifier

rf_balanced = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_balanced.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [28]:
from sklearn.metrics import classification_report

y_pred_balanced = rf_balanced.predict(X_test)

print(classification_report(y_test, y_pred_balanced))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      9634
           1       0.45      0.66      0.54       297

    accuracy                           0.97      9931
   macro avg       0.72      0.82      0.76      9931
weighted avg       0.97      0.97      0.97      9931

In [29]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(20)

                        Feature  Importance
0                           age    0.603398
1             length_of_service    0.188437
108            gender_full_Male    0.048140
2                    store_name    0.036173
36          city_name_Vancouver    0.009269
38           city_name_Victoria    0.006276
98      job_title_Produce Clerk    0.005462
21   city_name_New Westminister    0.005372
12        city_name_Fort Nelson    0.005257
95        job_title_Meat Cutter    0.004548
14        city_name_Grand Forks    0.003852
58      department_name_Produce    0.003566
56        department_name_Meats    0.003317
28          city_name_Princeton    0.003129
16           city_name_Kamloops    0.003126
15              city_name_Haney    0.003064
40         city_name_White Rock    0.002486
6             city_name_Burnaby    0.002366
32             city_name_Surrey    0.002293
10       city_name_Dawson Creek    0.002283

In [30]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

et.fit(X_train, y_train)

ExtraTreesClassifier(n_jobs=-1, random_state=42)

In [31]:
y_pred_et = et.predict(X_test)

In [32]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_et))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      9634
           1       0.80      0.50      0.62       297

    accuracy                           0.98      9931
   macro avg       0.89      0.75      0.80      9931
weighted avg       0.98      0.98      0.98      9931

In [33]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [34]:
y_pred_gb = gb.predict(X_test)

In [35]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_gb))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      9634
           1       0.99      0.55      0.71       297

    accuracy                           0.99      9931
   macro avg       0.99      0.78      0.85      9931
weighted avg       0.99      0.99      0.98      9931

In [36]:
probs = rf.predict_proba(X_test)[:, 1]

In [37]:
probs = rf.predict_proba(X_test)[:, 1]

print(probs[:10])

[0.      0.13328 0.26    0.      0.      0.      0.      0.      0.
 0.     ]

In [38]:
from sklearn.metrics import classification_report

y_pred_30 = (probs >= 0.30).astype(int)

print(classification_report(y_test, y_pred_30))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      9634
           1       0.71      0.68      0.70       297

    accuracy                           0.98      9931
   macro avg       0.85      0.84      0.84      9931
weighted avg       0.98      0.98      0.98      9931